name: Add Project Item

on:
  issues:
    types: [opened]

jobs:
  add_project_item:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PROJECT_OWNER: RISHIKESHk07
      PROJECT_URL: https://github.com/RISHIKESHk07/hello-react/issues/
      PROJECT_ID: 1

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Add to project
      run: |
        gh project item-add ${{ env.PROJECT_ID }} --owner ${{ env.PROJECT_OWNER }} --url ${{ env.PROJECT_URL }}${{ github.event.issue.number }}
