name: Add Project Item

on:
  issues:
    types: [opened]

jobs:
  add_project_item:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Add project item
        run: |
          gh project item-add 1 --owner RISHIKESHk07 --url ${{ github.event.issue.html_url }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
