name: Add Project Item

on:
  issues:
    types: [opened]

jobs:
  add_project_item:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get repository owner and name
      id: repo_info
      run: |
        echo "OWNER=$(echo ${GITHUB_REPOSITORY} | cut -d '/' -f 1)" >> $GITHUB_ENV
        echo "REPO=$(echo ${GITHUB_REPOSITORY} | cut -d '/' -f 2)" >> $GITHUB_ENV

    - name: Get project ID
      id: project_info
      run: |
        project_id=$(gh api graphql -f query='query {
          repository(owner: "${{ env.OWNER }}", name: "${{ env.REPO }}") {
            projects(first: 1) {
              nodes {
                id
              }
            }
          }
        }' | jq -r '.data.repository.projects.nodes[0].id')
        echo "PROJECT_ID=$project_id" >> $GITHUB_ENV

    - name: Add to project
      run: |
        gh project item-add $PROJECT_ID --url ${{ github.event.issue.html_url }}
           
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
