name: Auto Assign to Project(s)

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]
  issue_comment:
    types: [created]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign NEW issues and NEW pull requests to project 1
      uses: actions/checkout@v3
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/RISHIKESHk07/hello-react/projects/1'

    - name: Assign issues and pull requests with `bug` label to project 2
      uses: actions/checkout@v3
      if: |
        contains(github.event.issue.labels.*.name, 'bug') ||
        contains(github.event.pull_request.labels.*.name, 'bug')
      with:
        project: 'https://github.com/RISHIKESHk07/hello-react/projects/2'
        column_name: 'Labeled'
